// Generated by CoffeeScript 1.10.0
(function() {
  var MainController;

  angular.module('app', ['ui.router']);

  MainController = (function() {
    MainController.$inject = ['$log'];

    function MainController($log) {
      var vm;
      vm = this;
      return;
    }

    return MainController;

  })();

  angular.module('app').controller('MainController', MainController);

  angular.element(document).ready(function() {
    angular.bootstrap(document, ['app']);
  });

}).call(this);

//# sourceMappingURL=app.js.map
