// Generated by CoffeeScript 1.10.0
(function() {
  var config;

  config = (function() {
    config.$inject = ['$stateProvider', '$urlRouterProvider'];

    function config($stateProvider, $urlRouterProvider) {
      $urlRouterProvider.when('/', '/report').otherwise('/');
      $stateProvider.state('report', {
        url: '/report',
        views: {
          filters: {
            templateUrl: './report/filters/filters.tpl.html',
            controller: 'FiltersController as filters'
          },
          tableData: {
            templateUrl: './report/tableData/tableData.tpl.html',
            controller: 'TableDataController as tableData'
          },
          graph: {
            templateUrl: './report/graph/graph.tpl.html',
            controller: 'GraphController as graph'
          }
        }
      });
      return;
    }

    return config;

  })();

  angular.module('app').config(config);

}).call(this);

//# sourceMappingURL=router.js.map
