// Generated by CoffeeScript 1.10.0
(function() {
  var HomeService;

  HomeService = (function() {
    HomeService.$inject = ['$timeout'];

    function HomeService($timeout) {
      return {
        getName: function() {
          return $timeout(function() {
            return 'coffeeScript';
          }, 2000);
        }
      };
    }

    return HomeService;

  })();

  angular.module('app').factory('HomeService', HomeService);

}).call(this);

//# sourceMappingURL=home.service.js.map
