// Generated by CoffeeScript 1.10.0
(function() {
  var DemoController;

  angular.module('demo', ['ngAnimate']);

  DemoController = (function() {
    DemoController.$inject = ['$log'];

    function DemoController($log) {
      var vm;
      $log.info(this);
      vm = this;
      vm.bool = false;
      vm.toggle = function() {
        vm.bool = !vm.bool;
      };
      return;
    }

    return DemoController;

  })();

  angular.module('demo').controller('DemoController', DemoController);

}).call(this);

//# sourceMappingURL=main.js.map
