// Generated by CoffeeScript 1.10.0
(function() {
  var DemoController;

  angular.module('demo', []);

  DemoController = function($log, $location, $anchorScroll) {
    var vm;
    vm = this;
    vm.model = {
      yOffset: 0
    };
    vm.fn = {
      goAnchor: function(anchor) {
        var oldHash;
        oldHash = $location.hash();
        $location.hash(anchor);
        $anchorScroll.yOffset = parseInt(vm.model.yOffset, 10);
        $anchorScroll();
        $location.hash(oldHash);
      }
    };
  };

  angular.module('demo').controller('DemoController', ['$log', '$location', '$anchorScroll', DemoController]);

}).call(this);

//# sourceMappingURL=main.js.map
