// Generated by CoffeeScript 1.10.0
(function() {
  var config;

  config = (function() {
    config.$inject = ['$stateProvider', '$urlRouterProvider'];

    function config($stateProvider, $urlRouterProvider) {
      var about, contact, contactDetail, contactList, home;
      $urlRouterProvider.when('/', 'home').otherwise('/home');
      home = {
        name: 'home',
        url: '/home',
        templateUrl: './home/home.tpl.html',
        controller: 'HomeController',
        controllerAs: 'home',
        resolve: {
          name: function(HomeService) {
            return HomeService.getName();
          }
        }
      };
      contact = {
        name: 'contact',
        url: '/contact',
        templateUrl: './contact/contact.tpl.html',
        controller: 'ContactController as contact'
      };
      contactList = {
        name: 'contact.list',
        url: '^/list',
        parent: contact,
        templateUrl: './contact/contactList/contactList.tpl.html',
        controller: 'ContactListController',
        controllerAs: 'contactList'
      };
      about = {
        name: 'about',
        params: {
          'aboutId': '123'
        },
        url: '/about/:aboutId',
        template: "<div class=\"container-fluid\">\n	<p>This is about page</p>\n</div>"
      };
      contactDetail = {
        name: 'contact.detail',
        url: '^/detail/{contactId}?from&to',
        parent: 'contact',
        templateUrl: './contact/contactDetail/contactDetail.tpl.html',
        controller: 'ContactDetailController',
        controllerAs: 'contactDetail'
      };
      $stateProvider.state(home).state(contact).state(contactList).state(contactDetail).state(about);
      return;
    }

    return config;

  })();

  angular.module('app').config(config);

}).call(this);

//# sourceMappingURL=router.js.map
