// Generated by CoffeeScript 1.10.0
(function() {
  var DemoController;

  angular.module('demo', ['ngAnimate']);

  DemoController = (function() {
    DemoController.$inject = ['$log'];

    function DemoController($log) {
      var vm;
      vm = this;
      vm.onOff = false;
      return;
    }

    return DemoController;

  })();

  angular.module('demo').controller('DemoController', DemoController);

}).call(this);

//# sourceMappingURL=main.js.map
